apiVersion: v1
kind: Secret
metadata:
  name: obs-credentials
  namespace: default
type: Opaque
data:
  # 使用 base64 编码你的密钥
  AWS_ACCESS_KEY_ID: HPUARDKHMCHV6TISR8ND
  AWS_SECRET_ACCESS_KEY: 6ggkLoDhaU8A4Uq6nIwzp2y5cZ97hg6PoTOTUInr