apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: perf-double
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: swr.cn-north-4.myhuaweicloud.com/ppy/pyspark:v9
  mainApplicationFile: local:///opt/spark/work/performance_query.py
  sparkVersion: "3.4.0"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: "512m"
    serviceAccount: spark
    coreRequest: "100m"
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: obs-credentials
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: obs-credentials
            key: AWS_SECRET_ACCESS_KEY
      - name: SPARK_EXECUTOR_INSTANCES
        value: "2"
    volumeMounts:
      - name: code
        mountPath: /opt/spark/work
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    coreRequest: "100m"
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: obs-credentials
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: obs-credentials
            key: AWS_SECRET_ACCESS_KEY
    volumeMounts:
      - name: code
        mountPath: /opt/spark/work
  volumes:
    - name: code
      configMap:
        name: perf-code
        items:
          - key: performance_query.py
            path: performance_query.py
  sparkConf:
    "spark.hadoop.fs.s3a.endpoint": "obs.cn-north-4.myhuaweicloud.com"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.connection.ssl.enabled": "true"
    "spark.hadoop.fs.s3a.aws.credentials.provider": "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.hadoop.fs.s3a.access.key": "HPUARDKHMCHV6TISR8ND"
    "spark.hadoop.fs.s3a.secret.key": "6ggkLoDhaU8A4Uq6nIwzp2y5cZ97hg6PoTOTUInr"